# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TapFontKit-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'TapSwiftFixes'

  # Pods for TapFontKit-iOS

  target 'TapFontKit-iOSTests' do
    # Pods for testing
  end

end

target 'TapFontKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapFontKitExample

  target 'TapFontKitExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TapFontKitExampleUITests' do
    # Pods for testing
  end

end
